

 <?php
   // $x = array('ifty', 19, 1.5, 'shiplu');
   // echo $x[3];


   // $y = array('ifty' => 10, 'rakyb' =>20, 'shiplu' => 40);
   // echo $y['shiplu'];



   // $shiplu = array('ifty'=> 1, 'rakyb'=> 2, 'dewan'=>4, 'shiplu'=>5);


     // Foreach Loop
     // foreach($shiplu as $single){
     //   echo $single;
     // }


      // Nested Foreach
      $x = array(
        array(10,'email'=>'spu@gmail.com',30),
        array(40,'email'=>'spu@gmail.com',60),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
        array(70,'email'=>'spu@gmail.com',90),
      );
      foreach($x as $value){
        echo $value['email'] . "<br>";
      }

 // print_r($x[1]);





   // Three types of array

   // 1. Indexing array
   // 2. Associative Array
   // 3. Multidimensional Array

 ?>
